### ISSUE TITLE
Display mit NewLine

### ISSUE THREAD

**Issue by WinMic** [WinMic/MM_Projects#4]
Dem Display das "\n" beibringen.

**Comment by jokazz** [comment]
Vielleicht ist es besser daraus 2 Funktionen zu schreiben. Eine mit \n und eine ohne (z.B. diplayprint und displayprintln) wie beim Serial print.

**Comment by WinMic** [comment]
Ich glaube es würde sogar schon eine Dummyfunktion genügen.
Diese müsste nur schauen durch wie viele "Leerzeichen" ein \n ersetzt werden müsste um den selben effekt zu erzielen. Sobald das \n nurch n*Leerzeichen ersetzt ist, können wir mit diesem neuen String die DisplayMasterfunktion aufrufen.
Dies würde weniger Programmspeicher belegen.

**Comment by WinMic** [comment]
Update:
Wenn ein Text gedruckt wird, der ein newline erhällt wird dieses nun durch so viele leerzeichen ersetzt, das die Zeile voll ist.

Steht in einer Zeile schon etwas drin, und es kommt ein Text mit newline, wird das newline starr durch die anzahl ersetzt, was dazu führt, dass die nächste zeile mit z.B. 3 Leerzeichen beginnt.
eine Korrektur um Displayposition%TFT_Zeichen_pro_zeile funktioniert nicht. Da die DisplayPosition erst von DisplayMaster verändert wird, aber die neue Funktion davor ist.

Long Story Short.
Es kann ein Text mit \n geschrieben werden. Der nächste satzt beginnt dann in einer neuen Zeile.
Es kann kein text mit \n in eine Zeile geschrieben werden, in der schon etwas steht, dies führt zu einem neuen Fehler.

Evtl. müsste man beide Funktionen mergen, da ich den DisplayPosition Counter ungerne an 2 stellen im Code Manipuliere. Das führt bei GlobalenVariablen schnell zu Chaos.

**Comment by WinMic** [comment]
Habe die Bugs ausgebaut.
Dafür musste ich aber folgendes löschen:
- Text wird nicht mehr nach überflüssigen Leerzeichen durchsucht.
- Beim Verschieben des Textes wird nicht mehr um die Anzahl an benötigten Zeichen verschoben, sondern immer um eine ganze Zeile. (Wenn wir nicht um eine Zeile verschieben, stehen die NewlineLeerzeichen nicht mehr an der richtigen Position)
